spring:
  application:
      name: nacos-sentinel-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8001
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
server:
  port: 8888
